baseurl: /

name: R Weekly Blog
author: RWeekly.org
description: Updates and News about R Weekly
incremental: false
permalink: /:title.html

markdown: kramdown
kramdown:
  input: GFM
  footnote_backlink: '&#8617;&#65038;'

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
  - jemoji
  - jekyll-seo-tag

sass:
  sass_dir:          _sass
  style:            :compressed

